import React, { useEffect, useState } from 'react';
import { Video, ArrowRight, LoaderCircle, LockKeyhole, X, Plus, RefreshCw, Activity, Check } from 'lucide-react';
import { api, signIn } from './api.js';
export const ACTIVE=['joining','waiting','needs_attention','in_meeting'];
const LABELS={scheduled:'Scheduled',joining:'Joining',waiting:'Waiting for host',needs_attention:'Needs attention',in_meeting:'In meeting',completed:'Completed',failed:'Failed',missed:'Missed',cancelled:'Stopped',interrupted:'Interrupted'};
export const format=(value,options={})=>new Intl.DateTimeFormat('en-IN',{timeZone:'Asia/Kolkata',...options}).format(new Date(value));
export const time=value=>format(value,{hour:'numeric',minute:'2-digit'});
const slotTime=value=>time(`2026-01-01T${value}:00+05:30`);
export function IconButton({title,children,...props}){return <button className="icon-button" title={title} aria-label={title} {...props}>{children}</button>;}
export function Badge({status}){return <span className={`badge ${status}`}><span/>{LABELS[status]||status}</span>;}
export function Heading({eyebrow,title,children,action}){return <div className="heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{children&&<p>{children}</p>}</div>{action}</div>;}
export function LiveClock({instant}){
  const [clock,setClock]=useState(Date.parse(instant));
  useEffect(()=>{const baseline=Date.parse(instant),start=performance.now();setClock(baseline);const timer=setInterval(()=>setClock(baseline+performance.now()-start),1000);return()=>clearInterval(timer);},[instant]);
  return <div className="live-clocks"><span><b>{format(clock,{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false})}</b> IST</span><span>{new Date(clock).toISOString().slice(11,19)} UTC</span></div>;
}
export function Login({onLogin}){
  const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  return <div className="login-page"><div className="login-art"><div className="brand-mark"><Video size={26}/></div><p className="eyebrow">MEETING DESK / PRIVATE WORKSPACE</p><h1>Your week.<br/>Under control.</h1><p>Fixed sessions. A saved Zoom browser.<br/>A clear record of every joining attempt.</p><div className="login-lines" aria-hidden="true"><div/><div/><div/></div><span className="login-footer">BUILT AROUND YOUR SCHEDULE.</span></div><div className="login-form"><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await signIn(email,password);onLogin();}catch(e){setError(e.message);}finally{setBusy(false);}}}><p className="eyebrow">SUPER ADMIN ACCESS</p><h2>Welcome to your desk.</h2><p>Sign in to manage your sessions and saved browser.</p><label htmlFor="email">Email address</label><input id="email" type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/><label htmlFor="password" className="password-label">Password</label><input id="password" type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<p role="alert" className="field-error">{error}</p>}<button className="primary" disabled={busy}>{busy?<LoaderCircle className="spin" size={17}/>:null}Sign in<ArrowRight size={17}/></button><div className="login-help"><LockKeyhole size={16}/>Private access. No public account registration.</div></form></div></div>;
}
export function Rule({rule,busy,run}){
  const [editing,setEditing]=useState(false),[url,setUrl]=useState(rule.url);
  return <div className="weekly-session"><div className="weekly-session-main"><div><h3>{rule.title}</h3><p>{slotTime(rule.start)} – {slotTime(rule.end)} <span>IST</span></p></div><span className={rule.url?'link-ready':'link-missing'}>{rule.url?'Registration link saved':'Link needed'}</span><button className="quiet" onClick={()=>{setUrl(rule.url);setEditing(!editing);}}>{editing?'Cancel':'Edit link'}</button><button className="auto-toggle" aria-label={`${rule.title} auto-join`} aria-pressed={rule.enabled} disabled={busy} onClick={()=>run(()=>api(`/rules/${rule.id}`,{title:rule.title,url:rule.url,enabled:!rule.enabled},'PUT'))}><span className={`toggle-track ${rule.enabled?'on':''}`}/>{rule.enabled?'Enabled':'Disabled'}</button></div>{editing&&<form className="rule-edit" onSubmit={e=>{e.preventDefault();run(async()=>{await api(`/rules/${rule.id}`,{title:rule.title,url,enabled:rule.enabled},'PUT');setEditing(false);},'Registration link updated.');}}><label>Registration URL<input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://your-organization.zoom.us/meeting/register/…"/></label><button className="primary" disabled={busy}>Save link</button></form>}</div>;
}
export function MeetingForm({settings,onClose,onSubmit,busy}){
  return <form className="meeting-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSubmit({title:f.get('title'),url:f.get('url'),startsAt:new Date(`${f.get('start')}:00+05:30`).toISOString(),endsAt:new Date(`${f.get('end')}:00+05:30`).toISOString(),displayName:f.get('displayName'),passcode:f.get('passcode'),autoJoin:false});}}><div className="section-heading"><h3>One-off test meeting</h3><IconButton type="button" title="Close form" onClick={onClose}><X size={18}/></IconButton></div><div className="form-grid"><label className="wide">Meeting title<input name="title" placeholder="Registration flow test" required maxLength={150} autoFocus/></label><label className="wide">Zoom meeting or registration link<input name="url" type="url" required placeholder="https://…zoom.us/meeting/register/…"/></label><label>Starts at (IST)<input name="start" type="datetime-local" required step="60"/></label><label>Ends at (IST)<input name="end" type="datetime-local" required step="60"/></label><p className="field-hint wide">Both times are interpreted as India Standard Time (UTC +05:30), regardless of this device’s timezone.</p><label>Participant name<input name="displayName" defaultValue={settings.displayName} required maxLength={80}/></label><label>Passcode (optional)<input name="passcode" type="password" autoComplete="off"/></label></div><div className="form-footer"><span className="muted">Saved with auto-join off. Use the play button when ready.</span><button className="primary" disabled={busy}><Plus size={16}/>Save test meeting</button></div></form>;
}
export function ActivityView({data}){
  const [events,setEvents]=useState([]),[error,setError]=useState(''),[loading,setLoading]=useState(true);
  async function load(){try{const result=await api('/activity');setEvents(result.events);setError('');}catch(e){setError(e.message);}finally{setLoading(false);}}
  useEffect(()=>{load();const timer=setInterval(load,10000);return()=>clearInterval(timer);},[]);
  return <><Heading eyebrow="DURABLE ACTIVITY HISTORY" title="An honest record of every attempt." action={<button className="secondary" onClick={load}><RefreshCw size={16}/>Refresh</button>}>Joining, waiting, confirmed admission and leaving. Stored in DuckDB, with timestamps in IST.</Heading>{error&&<div className="message error" role="alert">{error}</div>}{loading?<div className="empty">Loading activity…</div>:events.length?<div className="activity-list">{events.map(event=><div className="activity-row" key={event.id}><span className="activity-dot"/><div><span className="event-kind">{event.kind.replaceAll('_',' ')}</span><p>{event.message}</p><small>{data.meetings.find(m=>m.id===event.meetingId)?.title||'Workspace'}</small></div><time>{format(event.at,{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',second:'2-digit'})} IST</time></div>)}</div>:<div className="empty"><Activity size={30}/><h3>No activity yet</h3><p>Events will appear as you use your workspace.</p></div>}</>;
}
export function Settings({data,busy,run,onPasswordChange}){
  const [prefs,setPrefs]=useState(data.settings);
  const field=key=>({value:prefs[key],onChange:e=>setPrefs({...prefs,[key]:e.target.value})});
  return <><Heading eyebrow="IDENTITY & PREFERENCES" title="Set up once. Stay in control.">Registration information is kept on your server and used for standard Zoom fields.</Heading><div className="settings-layout"><form className="settings-section" onSubmit={e=>{e.preventDefault();run(()=>api('/settings',prefs,'PUT'),'Preferences saved.');}}><h2>Registration profile</h2><p>Use the identity accepted by the meeting host. Custom questions remain yours to complete.</p><div className="form-grid"><label>First name<input {...field('firstName')} maxLength={80}/></label><label>Last name<input {...field('lastName')} maxLength={80}/></label><label className="wide">Registration email<input type="email" {...field('email')}/></label><label className="wide">Participant name<input {...field('displayName')} required maxLength={80}/></label><label>Schedule timezone<input value="India Standard Time · UTC +05:30" readOnly/></label><label>Open meetings early<select value={prefs.joinEarlyMinutes} onChange={e=>setPrefs({...prefs,joinEarlyMinutes:Number(e.target.value)})}>{[0,1,2,5,10,15].map(n=><option value={n} key={n}>{n} minutes before</option>)}</select></label></div><button className="primary settings-save" disabled={busy}><Check size={16}/>Save preferences</button></form><section className="settings-section"><h2>Poll automation</h2><p>Waiting for your test meeting and the poll HTML/selectors. The current app never selects or submits an answer.</p><div className="poll-timing"><div><span>Expected appearance</span><strong>+ 1h 45m</strong></div><ArrowRight size={20}/><div><span>Intended response</span><strong>+ 1h 50m</strong></div></div><p className="muted">These offsets use the scheduled session start. A manual-action event is logged at the expected window if the bot is in the meeting.</p></section><form className="settings-section" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{await api('/account/password',{currentPassword:f.get('current'),password:f.get('new')});onPasswordChange();});}}><h2>Super admin account</h2><p>{data.user.email} · No public sign-up. Only this admin can access meetings and the remote browser.</p><div className="form-grid"><label>Current password<input name="current" type="password" autoComplete="current-password" required/></label><label>New password<input name="new" type="password" autoComplete="new-password" minLength={16} maxLength={256} required/></label></div><button className="secondary settings-save" disabled={busy}>Change password and sign out</button></form><section className="settings-section"><h2>Server clock</h2><p>{data.istTime}</p><div className="server-clock-details"><code>{data.serverTime}</code><span>Runtime timezone: {data.serverTimezone}</span><span>Scheduling timezone: Asia/Kolkata</span></div></section></div></>;
}
