import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { CalendarDays, Monitor, SlidersHorizontal, Plus, ArrowUpRight, ArrowRight, Play, Pause, Clock3, Check, X, LogOut, Video, Trash2, Square, AlertCircle, ShieldCheck, ChevronRight, LoaderCircle, ExternalLink, LayoutDashboard, Activity, ListChecks } from 'lucide-react';
import '@fontsource-variable/dm-sans';
import '@fontsource-variable/manrope';
import { api } from './api.js';
import { Login, Rule, MeetingForm, ActivityView, Settings, LiveClock, Heading, Badge, IconButton, format, time, ACTIVE } from './components.jsx';
import './styles.css';

const DAYS=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const NAV=[['overview','Overview',LayoutDashboard],['weekly','Weekly schedule',CalendarDays],['browser','Live browser',Monitor],['activity','Activity',Activity],['settings','Settings',SlidersHorizontal]];
function App() {
  const [session,setSession]=useState(null),[data,setData]=useState(null),[view,setView]=useState(location.hash.slice(1)||'overview');
  const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[adding,setAdding]=useState(false),[filter,setFilter]=useState('upcoming');
  async function refresh(){setData(await api('/state'));}
  useEffect(()=>{
    api('/session').then(s=>setSession(s.authenticated)).catch(e=>setError(e.message));
    const signOut=()=>{setSession(false);setData(null);};
    const hash=()=>setView(NAV.some(([key])=>key===location.hash.slice(1))?location.hash.slice(1):'overview');
    window.addEventListener('signed-out',signOut);window.addEventListener('hashchange',hash);
    return()=>{window.removeEventListener('signed-out',signOut);window.removeEventListener('hashchange',hash);};
  },[]);
  useEffect(()=>{if(!session)return;refresh().catch(e=>setError(e.message));const timer=setInterval(()=>refresh().catch(e=>setError(e.message)),5000);return()=>clearInterval(timer);},[session]);
  async function run(fn,success=''){setBusy(true);setError('');setNotice('');try{await fn();await refresh();setNotice(success);}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function logout(){try{await api('/logout',{});setSession(false);setData(null);}catch(e){setError(e.message);}}
  const go=tab=>{location.hash=tab;};
  if(session===null)return <div className="loading"><LoaderCircle className="spin"/><p>{error||'Opening your workspace…'}</p>{error&&<button onClick={()=>location.reload()}>Retry</button>}</div>;
  if(!session)return <Login onLogin={()=>{setSession(true);setError('');}}/>;
  if(!data)return <div className="loading"><LoaderCircle className="spin"/><p>{error||'Loading your schedule…'}</p></div>;
  const upcoming=data.meetings.filter(m=>m.status==='scheduled'||ACTIVE.includes(m.status));
  const live=data.meetings.find(m=>ACTIVE.includes(m.status));
  const next=upcoming.find(m=>m.autoJoin&&m.status==='scheduled');
  const history=data.meetings.filter(m=>!upcoming.includes(m)).reverse();
  const visible=filter==='upcoming'?upcoming.slice(0,10):history;
  const activeView=NAV.find(([key])=>key===view)?.[1]||'Overview';
  return <div className="app-shell">
    <aside className="sidebar"><a className="brand" href="#overview"><span className="brand-mark"><Video size={23}/></span><span>meeting<span className="brand-light">desk</span><small>PRIVATE SESSION CONTROL</small></span></a><div className="nav-label">WORKSPACE</div><nav aria-label="Main navigation">{NAV.map(([key,label,Icon])=><a key={key} href={`#${key}`} className={view===key?'selected':''} aria-current={view===key?'page':undefined}><Icon size={19}/>{label}{key==='browser'&&live&&<span className="nav-dot"/>}</a>)}</nav><div className="sidebar-bottom"><div className="owner-chip"><span>{data.user.name.split(' ').filter(Boolean).map(s=>s[0]).slice(0,2).join('')}</span><div><strong>{data.user.name}</strong><small>Super admin</small></div><ShieldCheck size={17}/></div><button className="logout" onClick={logout}><LogOut size={16}/>Sign out</button></div></aside>
    <main><header className="topbar"><span>Workspace<ChevronRight size={13}/>{activeView}</span><div className="topbar-right"><LiveClock instant={data.serverTime}/><IconButton title="Sign out" onClick={logout}><LogOut size={16}/></IconButton></div></header><div className="page">
      {error&&<div className="message error" role="alert"><AlertCircle size={18}/><span>{error}</span><IconButton title="Dismiss error" onClick={()=>setError('')}><X size={16}/></IconButton></div>}
      {notice&&<div className="message success" role="status"><Check size={18}/><span>{notice}</span><IconButton title="Dismiss notice" onClick={()=>setNotice('')}><X size={16}/></IconButton></div>}
      {view==='overview'&&<>
        <Heading eyebrow={format(data.serverTime,{weekday:'long',day:'numeric',month:'long'})} title="Your sessions, under control." action={<button className="primary" onClick={()=>setAdding(!adding)}><Plus size={17}/>Add test meeting</button>}>A fixed weekly rhythm. A clear record of what actually happened.</Heading>
        <div className={`scheduler-strip ${data.settings.paused?'is-paused':''}`}><span className="status-light"/><div><strong>{data.settings.paused?'Scheduler paused':data.browser.loginOpen?'Zoom sign-in in progress':'Weekly scheduler enabled'}</strong><p>{data.settings.paused?'Sign in to Zoom and test a meeting before enabling weekly joins.':`Sessions open ${data.settings.joinEarlyMinutes} minutes early, using Indian Standard Time.`}</p></div><button className="quiet" disabled={busy} onClick={()=>run(()=>api('/settings',{...data.settings,paused:!data.settings.paused},'PUT'))}>{data.settings.paused?<Play size={15}/>:<Pause size={15}/>} {data.settings.paused?'Enable':'Pause'}</button></div>
        {adding&&<MeetingForm settings={data.settings} busy={busy} onClose={()=>setAdding(false)} onSubmit={values=>run(async()=>{await api('/meetings',values);setAdding(false);},'Test meeting added. Auto-join stays off until you enable it.')} />}
        <div className="overview"><section className="next-meeting"><div className="section-kicker"><span>{live?'ACTIVE SESSION':'NEXT SCHEDULED SESSION'}</span><Video size={19}/></div><h2>{(live||next)?.title||'Ready for your first test.'}</h2>{live||next?<><p className="next-date">{format((live||next).startsAt,{weekday:'long',day:'numeric',month:'short'})}<span>·</span>{time((live||next).startsAt)} – {time((live||next).endsAt)} IST</p><div className="next-bottom"><Badge status={(live||next).status}/><button onClick={()=>go(live?'browser':'weekly')}>{live?'Open live browser':'View weekly schedule'}<ArrowUpRight size={16}/></button></div>{data.settings.paused&&<p className="next-warning">Auto-join is paused.</p>}</>:<><p>Add a one-off link or configure the registration URLs in your weekly schedule.</p><button className="text-link" onClick={()=>setAdding(true)}>Add a test link<ArrowRight size={17}/></button></>}</section><section className="connections"><h3>Before your next session</h3><div className="connection-row"><Monitor size={21}/><div><strong>Saved Zoom browser</strong><small>{data.browser.loginOpen?'Finish sign-in in Live browser':data.browser.running?'Running · identity checked on join':'Open the browser and sign in with Google'}</small></div><IconButton title="Open live browser" onClick={()=>go('browser')}><ArrowUpRight size={18}/></IconButton></div><div className="connection-row"><ListChecks size={21}/><div><strong>Poll response</strong><small>Pending your test link, poll HTML and answers</small></div><span className="pending-label">Not configured</span></div><p className="connection-foot">Poll window: +1h 45m. Intended response: +1h 50m.<br/>No poll answers are submitted automatically yet.</p></section></div>
        <div className="fact-strip"><div><span>Weekly sessions</span><strong>{data.rules.length}</strong></div><div><span>Confirmed joins</span><strong>{data.meetings.filter(m=>m.joinedAt).length}</strong></div><div><span>Need attention</span><strong>{data.meetings.filter(m=>['needs_attention','failed','interrupted'].includes(m.status)).length}</strong></div><div><span>Schedule timezone</span><strong className="small-fact">IST <small>UTC +05:30</small></strong></div></div>
        <section className="schedule-section"><div className="section-heading"><div className="tabs" role="group" aria-label="Meeting filter"><button className={filter==='upcoming'?'chosen':''} onClick={()=>setFilter('upcoming')}>Upcoming<span>{upcoming.length}</span></button><button className={filter==='history'?'chosen':''} onClick={()=>setFilter('history')}>History</button></div><span className="muted">{filter==='upcoming'?'Next 10 sessions · all times IST':'Actual join and leave evidence'}</span></div>{visible.length?<div className="meeting-list">{visible.map(m=><MeetingRow key={m.id} meeting={m} busy={busy} data={data} run={run}/>)}</div>:<div className="empty"><CalendarDays size={29}/><h3>{filter==='upcoming'?'No upcoming sessions':'No attempts yet'}</h3><p>{filter==='upcoming'?'Add registration URLs in Weekly schedule, or use a test link.':'Joining attempts and outcomes will appear here.'}</p></div>}</section>
      </>}
      {view==='weekly'&&<><Heading eyebrow="REPEATS EVERY WEEK · ASIA/KOLKATA" title="Your week, already planned.">Eight sessions across seven days. The server’s timezone does not change these times.</Heading><div className="weekly-list">{DAYS.map((day,index)=><section className="weekday" key={day}><div className="weekday-name"><span>{String(index+1).padStart(2,'0')}</span><h2>{day}</h2></div><div className="weekday-sessions">{data.rules.filter(r=>r.weekday===index).map(rule=><Rule key={rule.id} rule={rule} busy={busy} run={run}/>)}</div></section>)}</div><div className="note"><Clock3 size={18}/><p>A 5:00 pm IST meeting starts at 11:30 am UTC. Saturday’s 10:00 am session starts at 4:30 am UTC. The next three weeks are generated automatically, with one browser session at a time.</p></div></>}
      {view==='browser'&&<><Heading eyebrow="YOUR PRIVATE ZOOM SESSION" title="See exactly what the bot sees.">Complete Google sign-in, registration questions or host verification in this browser.</Heading><div className="browser-toolbar"><div><span className={`status-light ${data.browser.running?'':'off'}`}/><strong>{data.browser.running?'Browser running':'Browser not started'}</strong>{live&&<Badge status={live.status}/>}</div><div className="button-group"><button className="secondary" disabled={busy||!!data.browser.activeMeetingId} onClick={()=>run(()=>api('/browser/login',{}),'Complete your Zoom sign-in, then click Done signing in.')}><Monitor size={16}/>Open Zoom sign-in</button>{data.browser.loginOpen&&<button className="primary" disabled={busy} onClick={()=>run(()=>api('/browser/finish-login',{}),'Browser released. Weekly scheduling follows the pause setting.')}><Check size={16}/>Done signing in</button>}{live&&<button className="danger" disabled={busy} onClick={()=>run(()=>api(`/meetings/${live.id}/stop`,{}))}><Square size={15}/>Stop meeting</button>}</div></div>{data.browser.desktopAvailable?<><iframe className="desktop-frame" title="Private Zoom remote browser" src="/desktop/vnc.html?autoconnect=true&resize=scale&path=desktop/websockify" allow="clipboard-read; clipboard-write"/><a className="text-link separate" href="/desktop/vnc.html?autoconnect=true&resize=remote&path=desktop/websockify" target="_blank" rel="noreferrer">Open in a separate tab<ExternalLink size={15}/></a></>:<div className="empty browser-placeholder"><Monitor size={38}/><h3>Your browser opens on this computer</h3><p>Use the local browser window after clicking Open Zoom sign-in. The embedded desktop is available in the Docker deployment.</p></div>}<div className="note"><AlertCircle size={18}/><p>Saved sign-in can expire. Zoom may request verification or host admission. The bot does not bypass these steps. Microphone and camera permissions stay off.</p></div>{data.browser.lastError&&<p className="field-error">{data.browser.lastError}</p>}</>}
      {view==='activity'&&<ActivityView data={data}/>}
      {view==='settings'&&<Settings data={data} busy={busy} run={run} onPasswordChange={()=>{setSession(false);setData(null);}}/>}
      <footer className="page-foot"><span><ShieldCheck size={14}/>Super-admin access only</span><span>Saved on your server · {data.audit.engine} activity archive{data.audit.pending?` · ${data.audit.pending} events pending`:''}</span></footer>
    </div></main></div>;
}
function MeetingRow({meeting:m,busy,data,run}) {
  return <article className="meeting-row"><div className="date-block"><span>{format(m.startsAt,{month:'short'})}</span><strong>{format(m.startsAt,{day:'2-digit'})}</strong></div><div className="meeting-info"><h3>{m.title}</h3><p>{format(m.startsAt,{weekday:'short'})} · {time(m.startsAt)} – {time(m.endsAt)} IST<span>·</span>{m.source==='weekly'?'Weekly':'Test / one-off'}</p>{m.detail&&<small>{m.detail}</small>}{m.joinedAt&&<small className="join-evidence">Joined {time(m.joinedAt)}{m.endedAt?` · Left ${time(m.endedAt)} · ${Math.floor((m.joinedSeconds||0)/60)} min observed`:' · Currently observed in Zoom'}</small>}{m.pollReminderAt&&<small className="poll-alert">Poll window reached. Open the browser to respond manually.</small>}</div><div className="row-state"><Badge status={m.status}/>{m.status==='scheduled'&&<button className="auto-toggle" disabled={busy} aria-pressed={m.autoJoin} onClick={()=>run(()=>api(`/meetings/${m.id}/toggle`,{}))}><span className={`toggle-track ${m.autoJoin?'on':''}`}/>{m.autoJoin?'Auto-join on':'Auto-join off'}</button>}</div><div className="row-actions">{ACTIVE.includes(m.status)?<IconButton title="Stop meeting" disabled={busy} onClick={()=>run(()=>api(`/meetings/${m.id}/stop`,{}))}><Square size={17}/></IconButton>:<>{Date.parse(m.endsAt)>Date.parse(data.serverTime)&&<IconButton title="Join meeting now" disabled={busy||!!data.browser.activeMeetingId||data.browser.loginOpen} onClick={()=>run(()=>api(`/meetings/${m.id}/join`,{}))}><Play size={17}/></IconButton>}<IconButton title={m.source==='weekly'?'Skip this occurrence':'Remove meeting'} disabled={busy} onClick={()=>run(()=>api(`/meetings/${m.id}/delete`,{}))}><Trash2 size={16}/></IconButton></>}</div></article>;
}
createRoot(document.getElementById('root')).render(<App/>);
